[project]
name = "course-agno"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=2.5.9",
    "chonkie[semantic]>=1.6.4",
    "chromadb>=1.5.8",
    "ddgs>=9.11.4",
    "fastapi>=0.135.2",
    "groq>=1.1.1",
    "openai>=2.29.0",
    "pypdf>=6.10.2",
    "python-dotenv>=1.2.2",
    "sqlalchemy>=2.0.48",
    "tavily-python>=0.7.23",
    "uvicorn>=0.42.0",
    "yfinance>=1.2.0",
]
